"use client";

import dynamic from "next/dynamic";

const components = {
  "percentage-calculator": dynamic(() => import("./percentage-calculator")), "age-calculator": dynamic(() => import("./age-calculator")), "discount-calculator": dynamic(() => import("./discount-calculator")),
  "time-converter": dynamic(() => import("./time-converter")), "time-zone-converter": dynamic(() => import("./time-zone-converter")), "emi-calculator": dynamic(() => import("./emi-calculator")), "gst-calculator": dynamic(() => import("./gst-calculator")), "hra-calculator": dynamic(() => import("./hra-calculator")), "bmi-calculator": dynamic(() => import("./bmi-calculator")), "sip-calculator": dynamic(() => import("./sip-calculator")),
  "unit-converter": dynamic(() => import("./unit-converter")), "date-calculator": dynamic(() => import("./date-calculator")), "fd-calculator": dynamic(() => import("./fd-calculator")), "compound-interest-calculator": dynamic(() => import("./compound-interest-calculator")), "income-tax-calculator": dynamic(() => import("./income-tax-calculator")), "salary-calculator": dynamic(() => import("./salary-calculator")), "ppf-calculator": dynamic(() => import("./ppf-calculator")), "currency-converter": dynamic(() => import("./currency-converter")), "gold-silver-rate-converter": dynamic(() => import("./gold-silver-converter")), "random-number-generator": dynamic(() => import("./random-number-generator")), "tip-calculator": dynamic(() => import("./tip-calculator")), "bill-splitter": dynamic(() => import("./bill-splitter")),
  "url-shortener": dynamic(() => import("./url-shortener")), "message-writer": dynamic(() => import("./message-writer")), "json-formatter": dynamic(() => import("./json-formatter")), "json-to-csv": dynamic(() => import("./json-to-csv")), "uuid-generator": dynamic(() => import("./uuid-generator")), "password-generator": dynamic(() => import("./password-generator")), "url-encoder-decoder": dynamic(() => import("./url-encoder")), "base64-encoder-decoder": dynamic(() => import("./base64")), "timestamp-converter": dynamic(() => import("./timestamp-converter")), "color-converter": dynamic(() => import("./color-converter")), "html-entity-encoder-decoder": dynamic(() => import("./html-entity")), "regex-tester": dynamic(() => import("./regex-tester")), "jwt-decoder": dynamic(() => import("./jwt-decoder")), "developer-file-viewer": dynamic(() => import("./developer-file-viewer")), "document-similarity-checker": dynamic(() => import("./document-similarity")),
  "pdf-difference-checker": dynamic(() => import("./pdf-difference-checker")), "pdf-visual-comparator": dynamic(() => import("./pdf-visual-comparator")), "pdf-layout-checker": dynamic(() => import("./pdf-layout-checker")), "pdf-text-extractor": dynamic(() => import("./pdf-text-extractor")), "pdf-metadata-viewer": dynamic(() => import("./pdf-metadata-viewer")), "pdf-page-analyzer": dynamic(() => import("./pdf-page-analyzer")), "pdf-merger": dynamic(() => import("./pdf-merger")), "pdf-splitter": dynamic(() => import("./pdf-splitter")), "pdf-to-images": dynamic(() => import("./pdf-to-images")), "images-to-pdf": dynamic(() => import("./images-to-pdf")), "pdf-compressor": dynamic(() => import("./pdf-compressor")), "image-similarity-checker": dynamic(() => import("./image-similarity-checker")), "screenshot-difference-checker": dynamic(() => import("./screenshot-difference-checker")), "image-metadata-viewer": dynamic(() => import("./image-metadata-viewer")), "image-dimension-checker": dynamic(() => import("./image-dimension-checker")), "document-compare": dynamic(() => import("./document-compare")),
  "word-counter": dynamic(() => import("./word-counter")), "character-counter": dynamic(() => import("./character-counter")), "case-converter": dynamic(() => import("./case-converter")), "text-cleaner": dynamic(() => import("./text-cleaner")), "remove-duplicate-lines": dynamic(() => import("./remove-duplicate-lines")), "url-slug-generator": dynamic(() => import("./slug-generator")), "text-diff-checker": dynamic(() => import("./text-diff")), "image-compressor": dynamic(() => import("./image-compressor")), "direct-video-downloader": dynamic(() => import("./direct-video-downloader")),
} as const;

export default function ToolRouter({ slug }: { slug: string }) {
  const Component = components[slug as keyof typeof components];
  if (!Component) return null;
  return <Component />;
}
