"use client";

import dynamic from "next/dynamic";

const DocumentCompareSuite = dynamic(() => import("./document-compare-suite"));
const ImageEditSuite = dynamic(() => import("./image-edit-suite"));
const ImageBase64Suite = dynamic(() => import("./image-base64-suite"));
const FileUtilitySuite = dynamic(() => import("./file-utility-suite"));
const QrCodeGenerator = dynamic(() => import("./qr-code-generator"));
const components = {
  "percentage-calculator": dynamic(() => import("./percentage-calculator")), "age-calculator": dynamic(() => import("./age-calculator")), "discount-calculator": dynamic(() => import("./discount-calculator")),
  "time-converter": dynamic(() => import("./time-converter")), "time-zone-converter": dynamic(() => import("./time-zone-converter")), "emi-calculator": dynamic(() => import("./emi-calculator")), "gst-calculator": dynamic(() => import("./gst-calculator")), "hra-calculator": dynamic(() => import("./hra-calculator")), "bmi-calculator": dynamic(() => import("./bmi-calculator")), "sip-calculator": dynamic(() => import("./sip-calculator")),
  "unit-converter": dynamic(() => import("./unit-converter")), "date-calculator": dynamic(() => import("./date-calculator")), "fd-calculator": dynamic(() => import("./fd-calculator")), "compound-interest-calculator": dynamic(() => import("./compound-interest-calculator")), "income-tax-calculator": dynamic(() => import("./income-tax-calculator")), "salary-calculator": dynamic(() => import("./salary-calculator")), "ppf-calculator": dynamic(() => import("./ppf-calculator")), "currency-converter": dynamic(() => import("./currency-converter")), "gold-silver-rate-converter": dynamic(() => import("./gold-silver-converter")), "random-number-generator": dynamic(() => import("./random-number-generator")), "tip-calculator": dynamic(() => import("./tip-calculator")), "bill-splitter": dynamic(() => import("./bill-splitter")), "qr-code-generator": QrCodeGenerator,
  "url-shortener": dynamic(() => import("./url-shortener")), "message-writer": dynamic(() => import("./message-writer")), "json-formatter": dynamic(() => import("./json-formatter")), "json-to-csv": dynamic(() => import("./json-to-csv")), "uuid-generator": dynamic(() => import("./uuid-generator")), "password-generator": dynamic(() => import("./password-generator")), "url-encoder-decoder": dynamic(() => import("./url-encoder")), "base64-encoder-decoder": dynamic(() => import("./base64")), "timestamp-converter": dynamic(() => import("./timestamp-converter")), "color-converter": dynamic(() => import("./color-converter")), "html-entity-encoder-decoder": dynamic(() => import("./html-entity")), "regex-tester": dynamic(() => import("./regex-tester")), "jwt-decoder": dynamic(() => import("./jwt-decoder")), "developer-file-viewer": dynamic(() => import("./developer-file-viewer")), "document-similarity-checker": dynamic(() => import("./document-similarity")),
  "pdf-difference-checker": () => <DocumentCompareSuite variant="pdf-difference-checker" />, "pdf-visual-comparator": () => <DocumentCompareSuite variant="pdf-visual-comparator" />, "pdf-layout-checker": () => <DocumentCompareSuite variant="pdf-layout-checker" />, "pdf-text-extractor": () => <DocumentCompareSuite variant="pdf-text-extractor" />, "pdf-metadata-viewer": () => <DocumentCompareSuite variant="pdf-metadata-viewer" />, "pdf-page-analyzer": () => <DocumentCompareSuite variant="pdf-page-analyzer" />, "pdf-merger": () => <DocumentCompareSuite variant="pdf-merger" />, "pdf-splitter": () => <DocumentCompareSuite variant="pdf-splitter" />, "pdf-to-images": () => <DocumentCompareSuite variant="pdf-to-images" />, "images-to-pdf": () => <DocumentCompareSuite variant="images-to-pdf" />, "pdf-compressor": () => <DocumentCompareSuite variant="pdf-compressor" />, "image-similarity-checker": () => <DocumentCompareSuite variant="image-similarity-checker" />, "screenshot-difference-checker": () => <DocumentCompareSuite variant="screenshot-difference-checker" />, "image-metadata-viewer": () => <DocumentCompareSuite variant="image-metadata-viewer" />, "image-dimension-checker": () => <DocumentCompareSuite variant="image-dimension-checker" />, "document-compare": () => <DocumentCompareSuite variant="document-compare" />,
  "word-counter": dynamic(() => import("./word-counter")), "character-counter": dynamic(() => import("./character-counter")), "case-converter": dynamic(() => import("./case-converter")), "text-cleaner": dynamic(() => import("./text-cleaner")), "remove-duplicate-lines": dynamic(() => import("./remove-duplicate-lines")), "url-slug-generator": dynamic(() => import("./slug-generator")), "text-diff-checker": dynamic(() => import("./text-diff")), "image-compressor": dynamic(() => import("./image-compressor")),
  "image-resizer": () => <ImageEditSuite variant="image-resizer" />, "image-cropper": () => <ImageEditSuite variant="image-cropper" />, "image-rotate-flip": () => <ImageEditSuite variant="image-rotate-flip" />, "image-format-converter": () => <ImageEditSuite variant="image-format-converter" />,
  "image-to-base64": () => <ImageBase64Suite variant="image-to-base64" />, "base64-to-image": () => <ImageBase64Suite variant="base64-to-image" />,
  "svg-to-png": () => <FileUtilitySuite variant="svg-to-png" />, "pdf-page-organizer": () => <FileUtilitySuite variant="pdf-page-organizer" />, "pdf-page-rotator": () => <FileUtilitySuite variant="pdf-page-rotator" />,
  "direct-video-downloader": dynamic(() => import("./direct-video-downloader")),
} as const;

export default function ToolRouter({ slug }: { slug: string }) {
  const Component = components[slug as keyof typeof components];
  if (!Component) return null;
  return <Component />;
}
