import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import PercentageCalculator from "@/components/tools/percentage-calculator";
import { tools } from "@/lib/tools";

const siteUrl = "https://internet-toolbox.example.com";

export function generateStaticParams() { return tools.map((tool) => ({ slug: tool.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const tool = tools.find((item) => item.slug === slug); if (!tool) return {}; return { title: `${tool.name} — Free Online Tool`, description: `${tool.description} Free, fast and easy to use online.`, alternates: { canonical: `${siteUrl}/tools/${tool.slug}` } }; }

export default async function ToolPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const tool = tools.find((item) => item.slug === slug);
  if (!tool) notFound();
  const Icon = tool.icon;
  return <main className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="container flex h-16 items-center justify-between"><a href="/" className="font-semibold tracking-tight text-slate-950">Internet Toolbox</a><a href="/" className="flex min-h-11 items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-950"><ArrowLeft size={16} /> All tools</a></div></header><section className="container py-10 md:py-14"><div className="mx-auto max-w-4xl"><nav aria-label="Breadcrumb" className="text-sm text-slate-500"><a href="/" className="hover:text-slate-900">Home</a><span className="mx-2" aria-hidden="true">/</span><span>{tool.name}</span></nav><div className="mt-8 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-2xl bg-blue-50 text-blue-700"><Icon size={22} /></div><p className="mt-5 text-sm font-semibold uppercase tracking-wider text-blue-600">{tool.category}</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-950 md:text-5xl">{tool.name}</h1><p className="mx-auto mt-4 max-w-2xl text-base leading-7 text-slate-600 md:text-lg">{tool.description}</p></div><div className="mt-9">{slug === "percentage-calculator" ? <PercentageCalculator /> : <div className="rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-sm"><p className="font-semibold text-slate-950">This tool is coming soon.</p><p className="mt-2 text-sm text-slate-500">We are building each utility carefully before marking it live.</p></div>}</div>{slug === "percentage-calculator" && <article className="mt-12 space-y-10"><section><h2 className="text-2xl font-bold tracking-tight text-slate-950">How to calculate a percentage</h2><p className="mt-3 leading-7 text-slate-600">To find a percentage of a number, multiply the number by the percentage and divide by 100. For example, 20% of 500 is 100.</p></section><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold text-slate-950">Percentage formula</h2><p className="mt-3 rounded-xl bg-slate-50 p-4 font-mono text-sm text-slate-800">Percentage of a number = (Number × Percentage) ÷ 100</p></section><section><h2 className="text-2xl font-bold tracking-tight text-slate-950">Frequently asked questions</h2><div className="mt-4 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white"><details className="p-5"><summary className="cursor-pointer font-semibold text-slate-950">What is 20% of 500?</summary><p className="mt-3 text-sm leading-6 text-slate-600">20% of 500 is 100.</p></details><details className="p-5"><summary className="cursor-pointer font-semibold text-slate-950">How do I calculate percentage increase?</summary><p className="mt-3 text-sm leading-6 text-slate-600">Multiply the original value by the percentage divided by 100, then add that amount to the original value.</p></details></div></section></article>}</div></section></main>;
}
