import { Calculator, CandlestickChart, Code2, FileText, ImageIcon, Link2, Palette, ShieldCheck, Sparkles, Type, Zap, GitCompare, ScanSearch, FileCode2 } from "lucide-react";

export type ToolCategory = "calculators" | "trading" | "everyday" | "developer" | "text" | "files";
export type Tool = { slug: string; name: string; description: string; category: ToolCategory; icon: typeof Calculator; status: "live" | "coming-soon" };

export const categories = [
  { slug: "calculators", name: "Money & Calculators", description: "Work out money, taxes, loans and returns.", icon: Calculator },
  { slug: "trading", name: "Trading & Investing", description: "Plan trade risk, position size, returns and portfolio scenarios.", icon: CandlestickChart },
  { slug: "everyday", name: "Everyday Tools", description: "Handle dates, time, units and everyday tasks.", icon: Zap },
  { slug: "developer", name: "Developer Tools", description: "Handle common coding and data tasks.", icon: Code2 },
  { slug: "text", name: "Text Tools", description: "Clean, count, write and change text.", icon: Type },
  { slug: "files", name: "File & Image Tools", description: "Handle PDFs, documents, images and common file tasks in your browser.", icon: ImageIcon },
] as const;

export const tools: Tool[] = [
  { slug: "percentage-calculator", name: "Percentage Calculator", description: "Work out percentages, increases and decreases.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "age-calculator", name: "Age Calculator", description: "Find an exact age between two dates.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "discount-calculator", name: "Discount Calculator", description: "Find the sale price and your savings.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "time-converter", name: "Time Converter", description: "Convert seconds, minutes, hours and days.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "time-zone-converter", name: "Time Zone Converter", description: "Convert a date and time between common world time zones.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "emi-calculator", name: "EMI Calculator", description: "Estimate monthly loan payments, interest and total repayment.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "gst-calculator", name: "GST Calculator", description: "Add or remove GST and see the tax amount.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "bmi-calculator", name: "BMI Calculator", description: "Calculate body mass index from height and weight.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "sip-calculator", name: "SIP Calculator", description: "Estimate SIP growth, returns and future value.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "unit-converter", name: "Unit Converter", description: "Convert length, weight, temperature and volume units.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "date-calculator", name: "Date Calculator", description: "Find date differences or add and subtract days.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "fd-calculator", name: "FD Calculator", description: "Estimate fixed deposit interest and maturity amount.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "compound-interest-calculator", name: "Compound Interest Calculator", description: "Calculate compound growth, interest and final amount.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "income-tax-calculator", name: "Income Tax Calculator", description: "Compare estimated income tax under the old and new regimes for FY 2026-27.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "salary-calculator", name: "Salary Calculator", description: "Estimate monthly in-hand salary from annual CTC.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "ppf-calculator", name: "PPF Calculator", description: "Estimate PPF growth, contributions and maturity value.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "hra-calculator", name: "HRA Calculator", description: "Estimate HRA exemption and taxable HRA.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "currency-converter", name: "Currency Converter", description: "Convert currencies using current reference exchange rates.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "gold-silver-rate-converter", name: "Gold & Silver Rate Converter", description: "Check gold and silver reference values in INR by weight and purity.", category: "calculators", icon: Calculator, status: "live" },
  { slug: "position-size-calculator", name: "Position Size Calculator", description: "Calculate trade quantity from account size, risk and stop-loss distance.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "risk-reward-calculator", name: "Risk / Reward Calculator", description: "Compare potential reward with the amount at risk on a trade.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "trading-profit-loss-calculator", name: "Trading Profit & Loss Calculator", description: "Estimate long or short trade profit and loss after fees.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "stop-loss-calculator", name: "Stop-Loss Calculator", description: "Calculate a stop price from entry, quantity and maximum planned risk.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "take-profit-calculator", name: "Take-Profit Calculator", description: "Calculate target prices from entry, stop-loss and an R multiple.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "trading-risk-calculator", name: "Trading Risk Calculator", description: "Calculate the cash amount represented by a chosen risk percentage.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "margin-calculator", name: "Margin Calculator", description: "Estimate required margin from position value and leverage.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "leverage-calculator", name: "Leverage Calculator", description: "Calculate effective leverage from capital and position value.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "break-even-calculator", name: "Break-Even Price Calculator", description: "Find the price needed to cover entry costs and trading fees.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "average-entry-price-calculator", name: "Average Entry Price Calculator", description: "Calculate the weighted average price across multiple buys.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "trading-expectancy-calculator", name: "Trading Win Rate & Expectancy Calculator", description: "Estimate expected profit or loss per trade from win rate and average outcomes.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "drawdown-calculator", name: "Trading Drawdown Calculator", description: "Measure account drawdown and the gain needed to recover it.", category: "trading", icon: CandlestickChart, status: "live" },
  { slug: "random-number-generator", name: "Random Number Generator", description: "Generate random integers in your browser.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "tip-calculator", name: "Tip Calculator", description: "Calculate a tip, final bill and each person's share.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "bill-splitter", name: "Bill Splitter", description: "Split a bill between people with an optional tip.", category: "everyday", icon: Calculator, status: "live" },
  { slug: "qr-code-generator", name: "QR Code Generator", description: "Create a downloadable QR code from text or a URL in your browser.", category: "everyday", icon: ScanSearch, status: "live" },
  { slug: "url-shortener", name: "URL Shortener", description: "Create a shorter, shareable link from a long URL.", category: "text", icon: Link2, status: "live" },
  { slug: "message-writer", name: "Caption & Message Writer", description: "Turn a few words into a ready-to-use caption, message or request.", category: "text", icon: Sparkles, status: "live" },
  { slug: "json-formatter", name: "JSON Formatter", description: "Format and inspect JSON with readable indentation.", category: "developer", icon: Code2, status: "live" },
  { slug: "json-to-csv", name: "JSON to CSV Converter", description: "Convert a JSON array of objects into downloadable CSV data in your browser.", category: "developer", icon: Code2, status: "live" },
  { slug: "uuid-generator", name: "UUID Generator", description: "Generate UUIDs in your browser.", category: "developer", icon: Code2, status: "live" },
  { slug: "password-generator", name: "Password Generator", description: "Generate strong passwords locally in your browser.", category: "developer", icon: ShieldCheck, status: "live" },
  { slug: "hash-generator", name: "Hash Generator", description: "Generate SHA-256, SHA-384 and SHA-512 hashes from text in your browser.", category: "developer", icon: ShieldCheck, status: "live" },
  { slug: "url-encoder-decoder", name: "URL Encoder / Decoder", description: "Encode or decode URL text in your browser.", category: "developer", icon: Code2, status: "live" },
  { slug: "base64-encoder-decoder", name: "Base64 Encoder / Decoder", description: "Encode or decode Base64 text.", category: "developer", icon: Code2, status: "live" },
  { slug: "timestamp-converter", name: "Unix Timestamp Converter", description: "Convert Unix timestamps and dates in either direction.", category: "developer", icon: Code2, status: "live" },
  { slug: "color-converter", name: "Color Converter", description: "Convert HEX, RGB and HSL color values.", category: "developer", icon: Palette, status: "live" },
  { slug: "html-entity-encoder-decoder", name: "HTML Entity Encoder / Decoder", description: "Convert HTML special characters to and from entities.", category: "developer", icon: Code2, status: "live" },
  { slug: "regex-tester", name: "Regex Tester", description: "Test regular expressions against text and inspect matches and capture groups.", category: "developer", icon: Code2, status: "live" },
  { slug: "jwt-decoder", name: "JWT Decoder", description: "Decode JWT headers and payloads locally without verifying the signature.", category: "developer", icon: ShieldCheck, status: "live" },
  { slug: "developer-file-viewer", name: "Developer File Viewer", description: "Open Markdown, HTML, CSS, JS, TS, JSON, YAML and XML files in your browser.", category: "developer", icon: Code2, status: "live" },
  { slug: "document-similarity-checker", name: "Document Similarity Checker", description: "Compare two PDFs for content, alignment, layout and visual similarity in your browser.", category: "files", icon: FileText, status: "live" },
  { slug: "pdf-difference-checker", name: "PDF Difference Checker", description: "Find added and removed readable text between two PDF versions.", category: "files", icon: GitCompare, status: "live" },
  { slug: "pdf-visual-comparator", name: "PDF Visual Comparator", description: "Render two PDFs and inspect matching pages visually side by side.", category: "files", icon: ScanSearch, status: "live" },
  { slug: "pdf-layout-checker", name: "PDF Layout Checker", description: "Compare PDF page sizes and text placement to spot layout shifts.", category: "files", icon: ScanSearch, status: "live" },
  { slug: "pdf-text-extractor", name: "PDF Text Extractor", description: "Extract readable text from a PDF locally in your browser.", category: "files", icon: FileText, status: "live" },
  { slug: "pdf-metadata-viewer", name: "PDF Metadata Viewer", description: "Inspect PDF page count, dimensions and basic document metadata.", category: "files", icon: FileText, status: "live" },
  { slug: "pdf-page-analyzer", name: "PDF Page Analyzer", description: "Analyze PDF page dimensions, orientation, text density and file size.", category: "files", icon: ScanSearch, status: "live" },
  { slug: "pdf-merger", name: "PDF Merger", description: "Combine multiple PDFs into one file locally.", category: "files", icon: FileText, status: "live" },
  { slug: "pdf-splitter", name: "PDF Splitter", description: "Extract selected pages from a PDF into a new file.", category: "files", icon: FileText, status: "live" },
  { slug: "pdf-to-images", name: "PDF to Images", description: "Render PDF pages as downloadable images in your browser.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "images-to-pdf", name: "Images to PDF", description: "Combine JPG and PNG images into a single PDF locally.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "pdf-compressor", name: "PDF Compressor", description: "Create a smaller, re-rendered PDF for sharing and storage.", category: "files", icon: FileText, status: "live" },
  { slug: "image-similarity-checker", name: "Image Similarity Checker", description: "Compare two images for visual similarity and dimensions.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "screenshot-difference-checker", name: "Screenshot Difference Checker", description: "Compare two screenshots and highlight how closely they match.", category: "files", icon: ScanSearch, status: "live" },
  { slug: "image-metadata-viewer", name: "Image Metadata Viewer", description: "Inspect image format, size, dimensions, aspect ratio and orientation.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "image-dimension-checker", name: "Image Dimension Checker", description: "Check exact image dimensions, aspect ratio, orientation and megapixels.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "document-compare", name: "Document Compare", description: "Compare two supported text documents for content changes.", category: "files", icon: GitCompare, status: "live" },
  { slug: "copy-paste-cleaner", name: "Copy-Paste Cleaner", description: "Remove Claude-style copy markers and tidy pasted text without rewriting it.", category: "text", icon: Sparkles, status: "live" },
  { slug: "word-counter", name: "Word Counter", description: "Count words, characters and reading time.", category: "text", icon: FileText, status: "live" },
  { slug: "character-counter", name: "Character Counter", description: "Count characters with and without spaces.", category: "text", icon: FileText, status: "live" },
  { slug: "case-converter", name: "Case Converter", description: "Change text between common letter cases.", category: "text", icon: Type, status: "live" },
  { slug: "text-cleaner", name: "Text Cleaner", description: "Remove extra spaces and blank lines from pasted text.", category: "text", icon: Type, status: "live" },
  { slug: "remove-duplicate-lines", name: "Remove Duplicate Lines", description: "Keep the first copy of each non-empty line.", category: "text", icon: Type, status: "live" },
  { slug: "url-slug-generator", name: "URL Slug Generator", description: "Turn page titles into clean URL slugs.", category: "text", icon: Type, status: "live" },
  { slug: "text-diff-checker", name: "Text Diff Checker", description: "Compare two texts and highlight added and removed lines.", category: "text", icon: Type, status: "live" },
  { slug: "image-compressor", name: "Image Compressor", description: "Compress JPG, PNG and WebP images in your browser.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "image-resizer", name: "Image Resizer", description: "Resize JPG, PNG and WebP images to exact dimensions in your browser.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "image-cropper", name: "Image Cropper", description: "Crop JPG, PNG and WebP images using exact pixel coordinates.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "image-rotate-flip", name: "Image Rotate & Flip", description: "Rotate images by 90°, 180° or 270° and flip them locally.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "image-format-converter", name: "Image Format Converter", description: "Convert between JPG, PNG and WebP formats in your browser.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "image-to-base64", name: "Image to Base64", description: "Convert an image into a copyable Base64 data URL locally.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "base64-to-image", name: "Base64 to Image", description: "Decode a Base64 image string into a preview and downloadable image locally.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "svg-to-png", name: "SVG to PNG", description: "Convert SVG markup into a PNG image in your browser.", category: "files", icon: ImageIcon, status: "live" },
  { slug: "pdf-page-organizer", name: "PDF Page Organizer", description: "Reorder or remove PDF pages and download the new document.", category: "files", icon: FileText, status: "live" },
  { slug: "pdf-page-rotator", name: "PDF Page Rotator", description: "Rotate an individual PDF page and download the updated document.", category: "files", icon: FileText, status: "live" },
  { slug: "structured-file-export", name: "Structured File Export", description: "Package any file as well-formed XML with metadata, checksum and encoded content.", category: "files", icon: FileCode2, status: "live" },
];

export const featuredTools = [tools[0], tools[5], tools[6], tools[7], tools[35], tools[36], tools[37], tools[38], tools[23], tools[8], tools[13], tools[17]];