export type TradingToolContent = {
  overview: string;
  bestFor: string;
  tip: string;
  limitation: string;
  faq: [string, string];
};

export const tradingToolContent: Record<string, TradingToolContent> = {
  "position-size-calculator": { overview: "Calculate a trade quantity from account size, planned risk and the distance between entry and stop-loss.", bestFor: "Position planning when you want to cap the amount at risk before deciding how many units to trade.", tip: "Calculate the quantity from the stop distance first, then check that the resulting position also fits your available capital and broker rules.", limitation: "The result does not account for slippage, liquidity, instrument-specific contract sizes or broker margin rules.", faq: ["How is position size calculated?", "The calculator divides your planned cash risk by the price distance between entry and stop-loss, then uses whole units."] },
  "risk-reward-calculator": { overview: "Compare the price distance to your target with the price distance to your stop-loss and express it as a risk-to-reward ratio.", bestFor: "Reviewing a planned setup before entering a trade and comparing potential reward against the amount exposed to loss.", tip: "A higher reward-to-risk ratio does not make a trade automatically good; consider probability, costs and the quality of the setup as well.", limitation: "The calculator measures price distances only and does not estimate the probability that either level will be reached.", faq: ["What does 1:2 risk-reward mean?", "It means the potential reward is twice the planned risk per unit or trade, based on the prices you entered."] },
  "trading-profit-loss-calculator": { overview: "Estimate gross and net profit or loss for a long or short trade after entering prices, quantity and total fees.", bestFor: "Checking the outcome of a completed or hypothetical trade before accounting for broker-specific statements.", tip: "Include both entry and exit costs where possible because fees can materially change small trades.", limitation: "Actual P&L can differ because of taxes, spreads, slippage, funding, contract multipliers and broker-specific charges.", faq: ["Does it support short trades?", "Yes. Choose Short and the calculator reverses the price-movement direction when calculating profit or loss."] },
  "stop-loss-calculator": { overview: "Calculate a stop-loss price from your entry price, position quantity and maximum cash amount you plan to risk.", bestFor: "Turning a fixed risk budget into a price level for a planned long or short position.", tip: "Treat the calculated level as a planning reference and check whether it makes sense relative to the market structure of the instrument.", limitation: "It assumes the full planned risk is represented by the entry-to-stop price distance and does not model gaps or execution slippage.", faq: ["Why are there separate long and short stop prices?", "A long position generally loses when price falls below entry, while a short position generally loses when price rises above entry."] },
  "take-profit-calculator": { overview: "Calculate target prices from an entry price, stop-loss distance and a chosen reward-to-risk multiple.", bestFor: "Planning target levels when a strategy defines exits using an R multiple rather than a fixed percentage.", tip: "Check that the calculated target is realistic for the instrument and timeframe instead of treating the mathematical target as a forecast.", limitation: "It does not account for market structure, volatility, probability, fees or whether the target is likely to fill.", faq: ["What is an R multiple?", "One R represents the planned risk distance from entry to stop; a 2R target places potential reward at twice that distance."] },
  "trading-risk-calculator": { overview: "Convert an account-level risk percentage into the maximum cash amount planned for one trade.", bestFor: "Setting a consistent risk budget before using a position-size or stop-loss calculation.", tip: "A fixed percentage can help keep risk consistent, but the appropriate risk level depends on your strategy and circumstances.", limitation: "This only calculates the planned amount at risk; it does not guarantee the actual loss will stay within that amount.", faq: ["What does 1% risk mean?", "It means the planned loss at the stop would equal 1% of the account value, before execution costs and slippage."] },
  "margin-calculator": { overview: "Estimate the capital required to support a position from its value and the leverage assumption you enter.", bestFor: "Understanding the basic relationship between position value, leverage and required capital.", tip: "Check your broker's actual margin schedule because requirements can change by instrument, volatility and account type.", limitation: "The simple calculation does not model maintenance margin, liquidation thresholds, intraday rules or broker-specific requirements.", faq: ["Is required margin always position value divided by leverage?", "That is the basic relationship used here, but actual broker margin requirements can differ substantially."] },
  "leverage-calculator": { overview: "Calculate effective leverage by comparing the total position value with the capital supporting it.", bestFor: "Understanding how much market exposure a position represents relative to the capital committed.", tip: "Look at leverage together with maximum loss and margin requirements because leverage can amplify losses as well as gains.", limitation: "Effective leverage does not describe every broker risk control, financing cost or liquidation rule.", faq: ["How is effective leverage calculated?", "It is position value divided by the capital used to support that position."] },
  "break-even-calculator": { overview: "Find the approximate price at which a long or short trade covers the entry value plus the round-trip fees you enter.", bestFor: "Understanding how transaction costs shift the price needed to finish a trade without a net loss.", tip: "Include all known round-trip trading costs rather than only the broker commission if you want a more useful estimate.", limitation: "It does not automatically include spreads, taxes, funding, exchange charges or other instrument-specific costs.", faq: ["Why is break-even above entry for a long trade?", "The price must rise enough to cover the fees that were paid in addition to the original entry price."] },
  "average-entry-price-calculator": { overview: "Calculate the weighted average entry price when multiple purchases are made at different prices and quantities.", bestFor: "Checking the blended entry price after adding to a position at more than one price.", tip: "Include the actual quantities for each fill; a simple average of the prices is only correct when the quantities are equal.", limitation: "This basic version does not include commissions, taxes or realized portions of a partially closed position.", faq: ["Why is a weighted average used?", "A larger purchase should have a larger influence on the combined entry price, so each price is weighted by its quantity."] },
  "trading-expectancy-calculator": { overview: "Estimate average expected profit or loss per trade from win rate, average winning trade and average losing trade.", bestFor: "Reviewing historical strategy performance and understanding how win rate and payoff interact.", tip: "Use results from a meaningful sample of trades and keep costs consistent; a tiny sample can give a misleading expectancy.", limitation: "Historical expectancy is not a guarantee of future performance and does not capture every dependency between trades.", faq: ["Can a strategy have a low win rate and still be profitable?", "Yes. If average wins are sufficiently larger than average losses, the calculated expectancy can still be positive."] },
  "drawdown-calculator": { overview: "Measure the percentage fall from an account peak to its current value and calculate the gain required to recover the loss.", bestFor: "Understanding portfolio or trading-account drawdowns and why recovering a loss requires a larger percentage gain.", tip: "Track both drawdown size and recovery requirement because the recovery percentage rises as the account falls further from its peak.", limitation: "It measures the values you provide and does not assess whether the drawdown is temporary, acceptable or caused by a particular strategy.", faq: ["Why does a 20% loss require a 25% gain to recover?", "After a 20% loss, the account is 80% of its peak, so it needs a 25% increase from that lower value to return to the original peak."] },
};
