import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import AllToolsBrowser from "@/components/all-tools-browser";

export const metadata = { title: "All Tools", description: "Browse and search every calculator, developer utility, text tool and file tool in Internet Toolbox." };

export default function ToolsPage() {
  return <main className="min-h-screen bg-[#f3f0e8] text-[#171717]"><header className="border-b border-[#d8d4c9] bg-[#f3f0e8]"><div className="container flex h-[68px] items-center justify-between"><Link href="/" className="flex items-center gap-3" aria-label="Internet Toolbox home"><span className="flex size-8 items-center justify-center border border-[#171717] bg-[#171717] text-xs font-bold text-white" aria-hidden="true">IT</span><span className="text-[15px] font-semibold tracking-[-0.01em]">Internet Toolbox</span></Link><Link href="/" className="flex min-h-11 items-center gap-2 rounded-md px-3 text-sm font-medium text-black/60 transition hover:bg-black/5 hover:text-[#171717]"><ArrowLeft size={15}/> Home</Link></div></header><section className="border-b border-[#d8d4c9] bg-[#e8e4d9] py-14 md:py-20"><div className="container"><p className="font-mono text-xs font-bold uppercase tracking-[0.18em] text-black/40">01 / Tool library</p><h1 className="mt-4 max-w-4xl text-5xl font-black tracking-[-0.045em] md:text-7xl">Every tool.<br/><span className="text-[#5f7429]">One place.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-black/55 md:text-lg">Browse the complete Internet Toolbox library. Search by task or filter by category to get to the right utility faster.</p></div></section><section className="container py-14 md:py-20"><AllToolsBrowser /></section><footer className="bg-[#171717] text-white"><div className="container flex flex-col gap-4 py-8 text-sm sm:flex-row sm:items-center sm:justify-between"><p className="font-semibold">Internet Toolbox</p><div className="flex flex-wrap gap-5 text-white/55"><Link href="/about" className="hover:text-white">About</Link><Link href="/privacy" className="hover:text-white">Privacy</Link><Link href="/support" className="hover:text-white">Support</Link><Link href="/" className="hover:text-white">Home</Link></div></div></footer></main>;
}
