import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, Check, LockKeyhole } from "lucide-react";
import SiteHeader from "@/components/site-header";
import ToolRouter from "@/components/tools/tool-router";
import { categories, tools } from "@/lib/tools";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://factoalbum.github.io/internet-toolbox";
export function generateStaticParams() { return tools.map((tool) => ({ slug: tool.slug })); }
function getCategory(slug: string) { return categories.find((category) => category.slug === slug); }
function getSeo(tool: (typeof tools)[number]) { const title = `${tool.name} - Free Online Tool`; return { title, description: `${tool.description} Use it free in your browser.`, intro: tool.description, uses: [`Open ${tool.name.toLowerCase()} without signing up`, "Enter your information and use the main action", "Review the result and download or copy it when available"] }; }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const tool = tools.find((item) => item.slug === slug); if (!tool) return {}; const seo = getSeo(tool); const toolUrl = `${siteUrl}/tools/${tool.slug}`; return { title: seo.title, description: seo.description, alternates: { canonical: toolUrl }, openGraph: { type: "website", title: `${seo.title} | Internet Toolbox`, description: seo.description, url: toolUrl }, twitter: { card: "summary", title: `${seo.title} | Internet Toolbox`, description: seo.description } }; }
export default async function ToolPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const tool = tools.find((item) => item.slug === slug); if (!tool) notFound(); const category = getCategory(tool.category); if (!category) notFound(); const Icon = tool.icon; const seo = getSeo(tool); const relatedTools = tools.filter((item) => item.category === tool.category && item.slug !== tool.slug && item.status === "live").slice(0, 3); const toolUrl = `${siteUrl}/tools/${tool.slug}/`; const categoryUrl = `${siteUrl}/categories/${category.slug}/`;
  const structuredData = [{ "@context": "https://schema.org", "@type": "WebApplication", name: tool.name, description: seo.description, url: toolUrl, applicationCategory: "UtilitiesApplication", operatingSystem: "Any", offers: { "@type": "Offer", price: "0", priceCurrency: "USD" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${siteUrl}/` }, { "@type": "ListItem", position: 2, name: category.name, item: categoryUrl }, { "@type": "ListItem", position: 3, name: tool.name, item: toolUrl }] }];
  return <main className="min-h-screen bg-[#faf9f6] text-[#171717]"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><SiteHeader /><section className="container py-6 md:py-9 lg:py-11"><div className="mx-auto max-w-5xl">
    <nav aria-label="Breadcrumb" className="mb-7 flex items-center gap-2 overflow-x-auto whitespace-nowrap text-xs font-semibold text-black/45"><Link href="/tools" className="inline-flex min-h-10 shrink-0 items-center gap-1.5 rounded-full border border-[#dedbd3] bg-white px-3.5 transition hover:border-[#171717] focus:outline-none focus:ring-4 focus:ring-[#c8f169]"><ArrowLeft size={13} />All tools</Link><span aria-hidden="true">/</span><Link href={`/categories/${category.slug}`} className="shrink-0 hover:text-black">{category.name}</Link><span aria-hidden="true">/</span><span className="truncate text-black">{tool.name}</span></nav>
    <header className="max-w-3xl"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-2xl bg-[#e8f4c9] text-[#435816]" aria-hidden="true"><Icon size={22} /></span><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-[#6d8e25]">{category.name}</p><p className="mt-0.5 text-xs font-medium text-black/40">Free browser tool</p></div></div><h1 className="mt-5 text-4xl font-black leading-[1] tracking-[-.055em] sm:text-5xl md:text-6xl">{tool.name}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-black/55 md:text-lg">{seo.intro}</p></header>
    <section data-tool-workspace className="mt-8 overflow-hidden rounded-3xl border border-[#dedbd3] bg-white shadow-[0_10px_30px_rgba(23,23,23,.045)] md:mt-10" aria-labelledby="workspace-title"><div className="flex items-center justify-between gap-4 border-b border-[#e8e5dd] px-5 py-4 md:px-6"><div className="min-w-0"><h2 id="workspace-title" className="text-sm font-black">Use the tool</h2><p className="mt-0.5 hidden text-xs text-black/40 sm:block">Enter your details below to get your result.</p></div><span className="inline-flex shrink-0 items-center gap-1.5 rounded-full bg-[#f2f6e8] px-3 py-1.5 text-[11px] font-bold text-[#52691f]"><LockKeyhole size={12} /> Runs in your browser</span></div><div className="min-w-0 overflow-hidden"><ToolRouter slug={slug} /></div></section>
    <section className="mt-10 border-t border-[#dedbd3] pt-8" aria-labelledby="tool-guide"><div className="grid gap-6 md:grid-cols-[.7fr_1.3fr] md:gap-12"><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-[#6d8e25]">Quick guide</p><h2 id="tool-guide" className="mt-2 text-2xl font-black tracking-[-.04em]">How it works</h2><p className="mt-2 text-sm leading-6 text-black/45">A simple three-step flow, with no account needed.</p></div><ol className="grid gap-2.5 sm:grid-cols-3 md:grid-cols-1">{seo.uses.map((use, index) => <li key={use} className="flex items-center gap-3 rounded-2xl border border-[#e3e0d8] bg-white p-4"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-[#171717] text-xs font-black text-white">{index + 1}</span><span className="text-sm font-semibold leading-5">{use}</span></li>)}</ol></div></section>
    {relatedTools.length > 0 && <section className="mt-10 border-t border-[#dedbd3] pt-8" aria-labelledby="related-tools"><div className="flex items-end justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.15em] text-[#6d8e25]">Related</p><h2 id="related-tools" className="mt-2 text-2xl font-black tracking-[-.04em]">You might also need</h2></div><Link href="/tools" className="hidden items-center gap-2 text-xs font-black sm:inline-flex">All tools <ArrowRight size={13} /></Link></div><div className="mt-4 grid gap-3 sm:grid-cols-3">{relatedTools.map((item) => <Link key={item.slug} href={`/tools/${item.slug}`} className="group rounded-2xl border border-[#e0ddd5] bg-white p-4 transition hover:-translate-y-0.5 hover:border-[#171717] hover:shadow-[0_8px_20px_rgba(23,23,23,.06)] focus:outline-none focus:ring-4 focus:ring-[#c8f169]"><span className="flex size-9 items-center justify-center rounded-xl bg-[#e8f4c9] text-[#435816]"><item.icon size={17} /></span><h3 className="mt-4 text-sm font-black">{item.name}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-black/45">{item.description}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#6d8e25]">Open tool <ArrowRight size={12} /></span></Link>)}</div></section>}
  </div></section><footer className="mt-3 border-t border-[#dedbd3] bg-[#171717] text-white"><div className="container flex flex-col gap-5 py-9 text-sm sm:flex-row sm:items-center sm:justify-between"><div><p className="font-black">Internet Toolbox</p><p className="mt-1 text-xs text-white/45">Small tools. Less hassle.</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-white/55"><Link href="/about">About</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link><Link href="/faq">FAQ</Link><Link href="/support">Support</Link><Link href="/tools" className="font-bold text-white">All tools</Link></div></div></footer></main>;
}
