import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Wrench } from "lucide-react";
import AgeCalculator from "@/components/tools/age-calculator";
import CharacterCounter from "@/components/tools/character-counter";
import DiscountCalculator from "@/components/tools/discount-calculator";
import JsonFormatter from "@/components/tools/json-formatter";
import PercentageCalculator from "@/components/tools/percentage-calculator";
import UuidGenerator from "@/components/tools/uuid-generator";
import WordCounter from "@/components/tools/word-counter";
import { tools } from "@/lib/tools";
export function generateStaticParams(){return tools.map(tool=>({slug:tool.slug}));}
export function generateMetadata({params}:{params:Promise<{slug:string}>}){return params.then(({slug})=>{const tool=tools.find(item=>item.slug===slug);return tool?{title:tool.name,description:`${tool.description} Free, fast and easy to use.`}:{};});}
export default async function ToolPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const tool=tools.find(item=>item.slug===slug);if(!tool)notFound();const Icon=tool.icon;return <main className="min-h-screen bg-[#f3f0e8] text-[#171717]"><header className="border-b border-[#d8d4c9] bg-[#f3f0e8]"><div className="container flex h-[68px] items-center justify-between"><Link href="/" className="flex items-center gap-3"><span className="flex size-8 items-center justify-center border border-[#171717] bg-[#171717] text-xs font-bold text-white">IT</span><span className="text-[15px] font-semibold">Internet Toolbox</span></Link><Link href="/tools" className="flex min-h-11 items-center gap-2 rounded-md px-3 text-sm font-medium text-black/60 hover:bg-black/5"><ArrowLeft size={15}/> All tools</Link></div></header><section className="container py-12 md:py-16"><div className="mx-auto max-w-5xl"><div className="flex items-start justify-between gap-8 border-b-2 border-[#171717] pb-8"><div><p className="font-mono text-xs font-bold uppercase tracking-[0.18em] text-black/40">Tool / {tool.category}</p><h1 className="mt-3 text-4xl font-black tracking-[-0.04em] md:text-6xl">{tool.name}</h1><p className="mt-4 max-w-2xl text-base leading-7 text-black/55 md:text-lg">{tool.description}</p></div><div className="hidden size-14 items-center justify-center rounded-xl bg-[#c8f169] md:flex"><Icon size={25}/></div></div><div className="mt-8">{slug==="percentage-calculator"&&<PercentageCalculator/>}{slug==="age-calculator"&&<AgeCalculator/>}{slug==="discount-calculator"&&<DiscountCalculator/>}{slug==="json-formatter"&&<JsonFormatter/>}{slug==="uuid-generator"&&<UuidGenerator/>}{slug==="word-counter"&&<WordCounter/>}{slug==="character-counter"&&<CharacterCounter/>}{!tool.status.includes("live")&&<div className="border border-[#d8d4c9] bg-[#fffdf8] p-8"><div className="flex min-h-64 flex-col items-center justify-center border border-dashed border-[#bcb8ae] text-center"><Wrench size={28}/><h2 className="mt-4 font-bold">Coming soon</h2><p className="mt-2 text-sm text-black/50">We are building this tool with the same fast, privacy-friendly experience.</p></div></div>}</div><article className="mt-10 grid gap-6 border-t border-[#d8d4c9] pt-8 md:grid-cols-[.35fr_.65fr]"><h2 className="font-mono text-xs font-bold uppercase tracking-[0.16em] text-black/40">About this tool</h2><p className="text-sm leading-7 text-black/55">Internet Toolbox provides simple online utilities designed to answer common questions quickly. Our tools work in your browser where practical, require no account, and are built with clear instructions and accessible controls.</p></article></div></section></main>}
